import { ROUTES } from "@/constants/routes";

export const GUEST_ONLY_ROUTES = [ROUTES.AUTH.LOGIN, ROUTES.AUTH.REGISTER];

export const CONTENT_MANAGE_ROUTES = [
  ROUTES.DASHBOARD.BASE,
  ROUTES.DASHBOARD.CONTENT.PLAYERS.BASE,
  ROUTES.DASHBOARD.CONTENT.CLUBS.BASE,
  ROUTES.DASHBOARD.CONTENT.NATIONALITIES.BASE,
  ROUTES.DASHBOARD.CONTENT.POSITIONS.BASE,
  ROUTES.DASHBOARD.CONTENT.REGIONS.BASE,
  ROUTES.DASHBOARD.CONTENT.CONFEDERATIONS.BASE,
  ROUTES.DASHBOARD.CONTENT.COMPETITIONS.BASE,
  // tambahkan route lain di sini
];

export const ADMIN_MANAGE_ROUTES = [
  ROUTES.DASHBOARD.BASE,
  ROUTES.DASHBOARD.SYSTEM.USERS.BASE,
  ROUTES.DASHBOARD.SYSTEM.ROLES,
];
