import { ROUTES } from "@/constants/routes";

export const CONTENT_MANAGE_ROUTES = [
  ROUTES.MANAGE.PLAYERS.BASE,
  ROUTES.MANAGE.CLUBS.BASE,
  ROUTES.MANAGE.NATIONALITIES,
  ROUTES.MANAGE.POSITIONS,
  ROUTES.MANAGE.SEASONS,
  ROUTES.MANAGE.REGIONS,
  ROUTES.MANAGE.COMPETITIONS.BASE,
  // tambahkan route lain di sini
];

export const ADMIN_MANAGE_ROUTES = [ROUTES.MANAGE.USERS.BASE];
